export type PipelineStep = {
  id: string;
  name: string;
  command: string;
  enabled: boolean;
};

export type PipelineDefinition = {
  shell: "bash" | "sh";
  steps: PipelineStep[];
};

export type ParsedPipeline = {
  definition: PipelineDefinition;
  structured: boolean;
};

const GENERATED_NOTICE =
  "# Generated by Shipyard Pipeline. Advanced edits are supported.";
const STEP_PREFIX = "# shipyard:step:";
const DISABLED_PREFIX = "# shipyard:disabled:";
const STEP_END_PREFIX = "# shipyard:end-step:";

export function createPipelineStepId() {
  return `step-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`;
}

function encode(value: string) {
  const bytes = new TextEncoder().encode(value);
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary)
    .replaceAll("+", "-")
    .replaceAll("/", "_")
    .replace(/=+$/, "");
}

function decode(value: string) {
  const base64 = value.replaceAll("-", "+").replaceAll("_", "/");
  const padded = base64.padEnd(Math.ceil(base64.length / 4) * 4, "=");
  const binary = atob(padded);
  return new TextDecoder().decode(
    Uint8Array.from(binary, (character) => character.charCodeAt(0)),
  );
}

function shellFrom(content: string): "bash" | "sh" {
  return /^#!.*\bbash(?:\s|$)/.test(content) ? "bash" : "sh";
}

function withoutShebang(content: string) {
  const lines = content.replaceAll("\r\n", "\n").split("\n");
  if (lines[0]?.startsWith("#!")) lines.shift();
  return lines
    .filter(
      (line) =>
        line !== GENERATED_NOTICE &&
        !line.startsWith(STEP_END_PREFIX) &&
        !line.startsWith(STEP_PREFIX),
    )
    .join("\n")
    .trim();
}

function inferredName(command: string, index: number) {
  const echo = command.match(/^\s*echo\s+["']?(.+?)["']?\s*$/m)?.[1];
  if (echo) {
    const cleaned = echo
      .replace(/\\?["']$/, "")
      .replace(/[^\p{L}\p{N}\s._-]+/gu, " ")
      .replace(/\s+/g, " ")
      .trim();
    if (cleaned) return cleaned.slice(0, 60);
  }

  const comment = command.match(/^\s*#\s+(.+)$/m)?.[1]?.trim();
  if (comment) return comment.slice(0, 60);

  const lower = command.toLowerCase();
  if (lower.includes("git pull")) return "Pull latest changes";
  if (/\b(?:pnpm|npm|yarn)\s+(?:install|i)\b/.test(lower))
    return "Install dependencies";
  if (/\b(?:pnpm|npm|yarn).*\bbuild\b/.test(lower)) return "Build application";
  if (/\bpm2\s+(?:reload|restart)\b/.test(lower)) return "Reload PM2 process";
  if (/\bflock\b/.test(lower)) return "Acquire deployment lock";
  if (/^\s*cd\s+/m.test(lower)) return "Change working directory";
  if (/^[A-Z_][A-Z0-9_]*=/m.test(command) || /\bexport\s+/m.test(command))
    return "Set deployment variables";
  return `Step ${index + 1}`;
}

function splitShellBlocks(content: string) {
  const lines = withoutShebang(content).split("\n");
  const blocks: string[] = [];
  let current: string[] = [];
  let heredocEnd: string | null = null;

  const flush = () => {
    const block = current.join("\n").trim();
    if (block) blocks.push(block);
    current = [];
  };

  for (const line of lines) {
    if (heredocEnd) {
      current.push(line);
      if (line.trim() === heredocEnd) heredocEnd = null;
      continue;
    }

    const heredoc = line.match(/<<-?\s*["']?([A-Za-z_][A-Za-z0-9_]*)["']?/);
    if (heredoc?.[1]) heredocEnd = heredoc[1];

    if (!line.trim()) {
      flush();
    } else {
      current.push(line);
    }
  }
  flush();
  return blocks;
}

function importedPipeline(content: string): ParsedPipeline {
  const blocks = splitShellBlocks(content);
  return {
    structured: false,
    definition: {
      shell: shellFrom(content),
      steps: blocks.map((command, index) => ({
        id: createPipelineStepId(),
        name: inferredName(command, index),
        command,
        enabled: true,
      })),
    },
  };
}

export function parsePipeline(content: string): ParsedPipeline {
  if (!content.includes(STEP_PREFIX)) return importedPipeline(content);

  try {
    const lines = content.replaceAll("\r\n", "\n").split("\n");
    const steps: PipelineStep[] = [];
    for (let index = 0; index < lines.length; index += 1) {
      const line = lines[index]!;
      if (!line.startsWith(STEP_PREFIX)) continue;
      const metadata = JSON.parse(decode(line.slice(STEP_PREFIX.length))) as {
        id: string;
        name: string;
        enabled: boolean;
      };
      const expectedEnd = `${STEP_END_PREFIX}${metadata.id}`;
      const body: string[] = [];
      index += 1;
      while (index < lines.length && lines[index] !== expectedEnd) {
        body.push(lines[index]!);
        index += 1;
      }
      if (index >= lines.length) throw new Error("Unclosed pipeline step");
      const disabled = body.find((entry) => entry.startsWith(DISABLED_PREFIX));
      const command = metadata.enabled
        ? body.join("\n").trim()
        : disabled
          ? decode(disabled.slice(DISABLED_PREFIX.length))
          : "";
      if (!metadata.id || !metadata.name || !command) {
        throw new Error("Invalid pipeline step");
      }
      steps.push({ ...metadata, command });
    }
    if (!steps.length) throw new Error("Pipeline has no steps");
    return {
      structured: true,
      definition: { shell: shellFrom(content), steps },
    };
  } catch {
    return importedPipeline(content);
  }
}

export function generatePipeline(definition: PipelineDefinition) {
  const shebang =
    definition.shell === "bash" ? "#!/usr/bin/env bash" : "#!/usr/bin/env sh";
  const sections = definition.steps.map((step) => {
    const metadata = encode(
      JSON.stringify({ id: step.id, name: step.name, enabled: step.enabled }),
    );
    const body = step.enabled
      ? step.command.trim()
      : `${DISABLED_PREFIX}${encode(step.command)}`;
    return `${STEP_PREFIX}${metadata}\n${body}\n${STEP_END_PREFIX}${step.id}`;
  });
  return `${shebang}\n\n${GENERATED_NOTICE}\n\n${sections.join("\n\n")}\n`;
}
